upstream django_app {
    server 127.0.0.1:8000;
}

proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=mycache:10m inactive=1h;

server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_types text/plain text/css application/javascript;

    location /uploads/ {
        alias /mnt/d/bmstu/tp_1/web/ask_nagdasev/uploads/;
        expires 30d;
    }

    location /static/ {
        alias /mnt/d/bmstu/tp_1/web/ask_nagdasev/static/;
        expires 30d;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_cache mycache;
        proxy_cache_valid 200 1m;
    }
}
